name: Automatic Preprocessing

on:
  push:
    branches: [ "main", "master" ]

jobs:
  run-preprocessing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      # Path Normal (Bersih)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Path Normal (Bersih)
      - name: Run Preprocessing Script
        run: |
          python preprocessing/automate_MRIZQY-PUTRA-P.py

      # Path Normal (Bersih)
      - name: Commit and Push Preprocessed Data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "ADVANCE: Preprocessing data completed"
          file_pattern: preprocessing/namadataset_preprocessing/*.csv
